modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL="https://github.com/JamCoreModding/reaping/issues"

[[mods]]
modId = "reaping"
version = "${file.jarVersion}"
displayName = "Reaping"
displayURL="https://github.com/JamCoreModding/reaping"
logoFile = "icon.png"
authors = "Jamalam"
description = '''
Harvest your animals in the most cursed way possible
'''

[[dependencies.reaping]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reaping]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reaping]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"
