modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL="https://github.com/JamCoreModding/reaping/issues"

[[mods]]
modId = "reaping"
version = "${file.jarVersion}"
displayName = "Reaping"
displayURL="https://github.com/JamCoreModding/reaping"
logoFile = "icon.png"
authors = "Jamalam"
description = '''
Harvest your animals in the most cursed way possible
'''

[[dependencies.reaping]]
modId = "neoforge"
mandatory = true
versionRange = "[20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reaping]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reaping]]
modId = "architectury"
mandatory = true
versionRange = "[10.0.17,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "reaping.mixins.json"
