modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL="https://github.com/JamCoreModding/reaping/issues"

[[mods]]
modId = "reaping"
version = "${file.jarVersion}"
displayName = "Reaping"
displayURL="https://github.com/JamCoreModding/reaping"
logoFile = "icon.png"
authors = "Jamalam"
description = '''
Harvest your animals in the most cursed way possible
'''

[[dependencies.reaping]]
modId = "neoforge"
type = "required"
versionRange = "[20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reaping]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reaping]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.reaping]]
modId = "jamlib"
type = "required"
versionRange = "[${jamlib_version},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "reaping.mixins.json"
